#pragma once

#define LEDC_TIMER LEDC_TIMER_0
#define LEDC_MODE LEDC_LOW_SPEED_MODE
#define LEDC_OUTPUT_IO (46)
#define LEDC_CHANNEL LEDC_CHANNEL_0
#define LEDC_DUTY_RES LEDC_TIMER_6_BIT
#define LEDC_DUTY (40)
#define LEDC_FREQUENCY (800000)

void on(void);
